@startuml
title 自販機システム_クラス図

class main {
    +{static}void システムを始動する()
} 

class functionCaller {
    /'
    1,2,3,9を入力させて機能を呼ぶなんてのはCUIならではなので、
    自販機の本質ではない。 自販機クラスから外へ出した
    '/
    +int 機能番号
    +void? 機能を呼ぶ()
}

class 自動販売機ソト {
    +int 投入金額
    +product 商品

    +初期画面を表示する()
    +void? お金を受け取る(int 投入金額)
    +void? 商品を販売する()
    +void? お金を返却する()
    +void? 自販機を終了する()
}

class 自販機ナカ_投入金額保管庫{
    +int 投入金額
    +上限を超えていないか計算する()
    +加算する()
}

class 自販機ナカ_商品保管庫 {
    /'
    ここに各商品の集合体が入っている感覚
    '/
    +int 商品在庫
    +在庫切れを検知する()
}

class 商品 {
    +int 商品番号
    +int 単価
    +String 商品名
}


/'
class 投入金額 {
    +int 投入された金額
    +boolean 上限を超えているかどうか

    +上限を超えているかどうか計算してみる()
}
int型の変数のやりとりで事足りるのではないか
'/

/'
class 初期画面 {
    表示する()
}
表示するという操作だけなら、自販機の中でいいのではないか
'/

@enduml