@startuml
title 自販機システム_UC01お金を投入する

actor 利用者
利用者 -> Main : システム実行

participant Main

Main -> UserInterface : new
activate UserInterface
Main -> 自動販売機 : new
activate 自動販売機

note over UserInterface #Cyan
[初期画面の表示]
end note
UserInterface -> 自動販売機 : get投入金額()
UserInterface <-- 自動販売機 : 現在の投入金額

UserInterface <- UserInterface : 初期画面を表示する()
    note over UserInterface
    商品番号 / 商品名 / 単価  / 在庫
    1 / おいしい水   / 100円 / 残り12本
    2 / サイコソーダ / 150円 / 残り5本
    3 / ミックスオレ / 160円 / 残り0本

    投入金額 [   0]円


    機能を選択してください
    [1] お金を投入する
    [2] 商品を購入する
    [3] 返金を受け取る
    [9] システムを終了する
    end note
deactivate UserInterface


利用者 -> UserInterface : 1を入力
activate UserInterface


UserInterface <- UserInterface : システムメッセージ01※
    note over UserInterface
    1000,500,100,50,10 のいずれかを入力してください
    end note
deactivate UserInterface


note over UserInterface #Orange
[お金を投入する]
end note
利用者 -> UserInterface : 希望金額を入力
'不正な入力はUIの段階で弾いておくべきではないか? 現実の自販機も異物は突っ込めない
'自分で定めた条件や、nextIntの例外を拾う
activate UserInterface

alt 正しい入力 (1000,500,100,50,10のいずれかの整数)

UserInterface -> 自動販売機 : 自動販売機.お金を投入する(int 希望金額)

自動販売機 -> checker : new
activate checker

自動販売機 -> checker : checker.上限チェック(int 希望金額, int 投入金額)

alt 上限チェックがfalse

自動販売機 <-- checker : false
UserInterface <-- 自動販売機 : false
UserInterface <- UserInterface : エラーメッセージ02※
    note over UserInterface
    ※ERROR_02
    投入できる金額の上限は9990円です
    end note
end

自動販売機 <-- checker : true
deactivate checker
自動販売機 <- 自動販売機 : [int 投入金額]に[int 希望金額]を加算する
UserInterface <-- 自動販売機 : true


else 不正な入力 (1000,500,100,50,10以外の整数、小数、負の数、int型のデータサイズを超える数)
UserInterface <- UserInterface : エラーメッセージ01※
    note over UserInterface
    ERROR_01:入力が正しくありません
    1000,500,100,50,10 のいずれかを入力してください
    end note

    note over UserInterface #Orange
    [お金を投入する]へ戻る
    end note
end

note over UserInterface #Cyan
[初期画面の表示]へ戻る
end note

@enduml