@startuml
title 自販機システム_クラス図

main -- 自動販売機
UserInterface -- 自動販売機
自動販売機 -- 投入金額マネージャ
投入金額マネージャ -- 投入金額


class main {
    +{static}void システムを始動する()
} 

/'
機能呼び出し - UserInterface
1,2,3,9を入力させて機能を呼ぶなんてのはCUIならではなので、
自販機の本質ではない。 自販機クラスから外へ出した
'/
class UserInterface {
    +boolean 機能を呼ぶ()
    +void 初期画面を表示する()
    /'
    1,2,3,9以外ならここでfalseを返し、エラーメッセージ00を表示
    '/
}

class 自動販売機 {
    +int お金を投入する()
    +product 商品を購入する()
    +int 返金を受け取る()
    +void 自販機を終了する()
}

class 投入金額マネージャ{
    +boolean 上限チェック()
    +int 投入金額に加算する()
    +int 投入金額を減算する()
}

class 投入金額 {
    +int 投入金額
    +getter()
    +setter()
}

class stock {
    /'
    ここに各商品の集合体が入っている感覚
    '/
    +int 商品の数量
    +boolean 在庫切れを検知する()
}

class product {
    +int 商品番号
    +int 単価
    +String 商品名
    +getter()
    +setter()
}


@enduml