@startuml
title 自販機システム_UC02商品を購入する

actor 利用者
note over UserInterface #Cyan
[初期画面を表示する]
end note

利用者 -> UserInterface : 2を入力

loop 登録している商品番号をすべて使って実施
activate UserInterface
UserInterface -> 自動販売機 : 自動販売機.get在庫数(int 商品番号)
activate 自動販売機
自動販売機 -> Storage : Storage.get在庫数(int 商品番号)
activate Storage
自動販売機 <-- Storage : 在庫数
deactivate Storage
UserInterface <-- 自動販売機 : 在庫数
deactivate 自動販売機
end loop

alt 少なくとも1商品は在庫がある
    UserInterface -> 自動販売機 : 自動販売機.get商品情報(int 商品番号)
    activate 自動販売機
    自動販売機 -> Storage : Storage.get商品情報(int 商品番号)
    activate Storage

    Storage -> Product : Product.get商品番号()
    activate Product
    Storage <-- Product : 商品番号
    deactivate Product
    自動販売機 <-- Storage : 商品情報 
    deactivate Storage
    UserInterface <-- 自動販売機 : 商品情報
    deactivate 自動販売機

    UserInterface <- UserInterface : システムメッセージ02を表示
    note over UserInterface
    --[2]商品を購入する--
    商品番号を入力してください
    1. おいしい水
    2. サイコソーダ
    3. ミックスオレ
    end note

else すべての商品の在庫が無い
    UserInterface <- UserInterface : エラーメッセージ03を表示
    note over UserInterface
    ERROR_03: すべての商品が売り切れています
    end note

end
deactivate UserInterface

利用者 -> UserInterface : 購入したい商品の番号を入力

activate UserInterface

alt 正しい入力 (自販機システム内に存在する、整数の商品番号)

    UserInterface -> 自動販売機 : 自動販売機.商品を購入する(int 商品番号)
    activate 自動販売機
    自動販売機 -> Storage : Storage.get在庫数(int 商品番号)
    activate Storage
    自動販売機 <-- Storage : 在庫数
    deactivate Storage

    alt 希望する商品の在庫が無い

        UserInterface -> UserInterface : エラーメッセージ06を表示
        note over UserInterface
        ERROR_06:ご指定の商品は売り切れています
        end note


    else 希望する商品の在庫がある

        自動販売機 -> Storage : Storage.get商品情報(int 商品番号)
        activate Storage
        Storage -> Product : Product.get商品番号()
        activate Product
        Storage <-- Product : 商品番号
        deactivate Product
        自動販売機 <-- Storage : 商品情報 
        deactivate Storage

        自動販売機 -> チェッカー : チェッカー.投入金額が足りているかチェックする(int 単価, int投入金額)
        activate チェッカー
        自動販売機 <-- チェッカー : チェック結果 true/false
        deactivate チェッカー

        alt (false) 投入金額　< 商品の単価

            UserInterface -> UserInterface : エラーメッセージ05を表示
            note over UserInterface
            ERROR_05:投入金額が不足しています
            お金を投入してください
            end note

        else (true) 投入金額 ≧ 商品の単価

            自動販売機 -> Storage : Storage.在庫を減らす()
            activate Storage
            Storage -> Storage : 購入した商品の[int 在庫]を1減らす
            自動販売機 -> 自動販売機 : [int 投入金額]から購入した商品の[int 単価]分だけ減算する
            deactivate Storage
            deactivate 自動販売機

            UserInterface -> UserInterface : システムメッセージ03を表示
            note over UserInterface
            ---お買い上げありがとうございます---
            [入力内容と対応した商品]を購入しました
            end note
            
        end


    end

else 不正な入力 (存在する商品番号以外の整数、小数、負の数、int型のデータサイズを超える数、文字列)
    UserInterface <- UserInterface : エラーメッセージ04を表示
    note over UserInterface
    ERROR_04:存在しない商品番号です
    正しく入力してください
    end note
  
end

note over UserInterface #Cyan
[初期画面を表示する]へ戻る
end note

@enduml